services:
  terapeut-backend:
    build: 
      context: ./server
      dockerfile: dockerfile
    container_name: terapeut-fastapi
    #command: sleep infinity
    ports:
      - "8000:8000"

  terapeut-frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: terapeut-nextjs
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://terapeut-fastapi:8000

networks:
  default:
    name: journalease-network
    external: true