services:
  terapeut-backend:
    build: 
      context: ./server
      dockerfile: dockerfile
    container_name: terapeut-fastapi
    command: sleep infinity
    ports:
      - "8000:8000"

networks:
  default:
    name: journalease-network
    external: true