# Use the official Python base image
FROM python:3-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN pip list

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
