services:
  journalease-mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - './data:/data/db'
    ports:
      - "27017:27017"

  journalease-nginx:
    image: nginx:latest
    container_name: nginx-journalease
    environment:
      DOMAIN: 127.0.0.1
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    networks:
      - default
    restart: always

networks:
  default:
    name: journalease-network